import { describe, expect, it } from 'vitest';

import * as brokerClient from './broker-client.ts';

describe('broker-client public entrypoint', () => {
  it('loads without starting privileged work and exposes only client contracts', () => {
    expect(Object.keys(brokerClient).toSorted()).toEqual([
      'BOOTSTRAP_NOT_READY_MAXIMUM_ATTEMPTS',
      'BOOTSTRAP_NOT_READY_MAXIMUM_DELAY_MS',
      'BOOTSTRAP_RESERVED_ENVIRONMENT_NAMES',
      'BROKER_BOOTSTRAP_BUILD_ID',
      'BROKER_BOOTSTRAP_CHILD_ARGUMENT',
      'BROKER_BOOTSTRAP_DEFAULT_TIMEOUT_MS',
      'BROKER_BOOTSTRAP_MAX_MESSAGE_BYTES',
      'BROKER_BOOTSTRAP_MAX_SECRET_CODE_UNITS',
      'BROKER_BOOTSTRAP_MAX_SLOTS',
      'BROKER_BOOTSTRAP_MAX_TIMEOUT_MS',
      'BROKER_BOOTSTRAP_PROTOCOL_VERSION',
      'BROKER_DEFAULT_OPERATION_TIMEOUT_MS',
      'BROKER_IPC_CHILD_ARGUMENT',
      'BROKER_MAX_DISCONNECT_DETAIL_LENGTH',
      'BROKER_MAX_MESSAGE_BYTES',
      'BROKER_MAX_OPERATION_TIMEOUT_MS',
      'BROKER_MAX_OUTPUT_CHUNK_BYTES',
      'BROKER_PROTOCOL_VERSION',
      'BROKER_REQUEST_CANCELLED_CODE',
      'MANAGED_ATTEMPT_ENVIRONMENT',
      'MANAGED_BUN_RECIPE_BROKER_ENTRYPOINT_ENVIRONMENT',
      'MANAGED_BUN_RECIPE_DEFAULT_RETRY_POLICY',
      'MANAGED_WINDOWS_JOB_ENVIRONMENT',
      'bunProcessEnvironmentNames',
      'clientErr',
      'clientOk',
      'clientTaskErr',
      'clientTaskOk',
      'clientTry',
      'clientTryAsync',
      'createBootstrapAcknowledgement',
      'createBootstrapNotReadyRetryPort',
      'createBootstrapRequest',
      'createBunBootstrapInheritedIpcRuntime',
      'createBunCooperativeBootstrapTransportPort',
      'createBunInheritedIpcRuntime',
      'createBunManagedAttemptEnvironmentPort',
      'createBunManagedWindowsJobFirstEffectGate',
      'createBunManagedWindowsJobNativePort',
      'createBunProcessEnvironmentInstallPort',
      'createBunProcessEnvironmentRuntime',
      'createManagedBootstrapRequest',
      'createManagedBunRecipeBootstrapRuntime',
      'createManagedWindowsJobFirstEffectGate',
      'decodeBootstrapProtocolJson',
      'decodeBootstrapProtocolMessage',
      'decodeBrokerControlJson',
      'decodeBrokerControlMessage',
      'encodeBrokerControlMessage',
      'isBootstrapResponseMessage',
      'openBrokerClientExchange',
      'parseBrokerAttemptId',
      'parseBrokerRequestId',
      'parseBrokerSequence',
      'parseBrokerTimestampMs',
      'planBootstrapEnvironmentPatch',
      'prepareManagedBunRecipeEnvironmentThenImport',
      'prepareRecipeEnvironment',
      'prepareRecipeEnvironmentThenImport',
      'prepareRecipeEnvironmentThenImportWithRetry',
      'prepareRecipeEnvironmentWithRetry',
      'readManagedWindowsJobFirstEffectIdentity',
      'reduceBrokerClientExchange',
      'reduceBrokerClientSession',
      'runBrokerControlOverInheritedIpc'
    ]);
    expect('Bun' in brokerClient).toBe(false);
  });
});
